M48
; DRILL file {KiCad 9.0.7} date 2026-05-23T11:20:34+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-23T11:20:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X92.79Y-85.195
X98.57Y-85.195
T2
X85.0Y-52.5
X85.0Y-87.5
X144.5Y-87.5
X145.0Y-52.5
M30
